<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Login Page</h1><br>
    <form action="/login" method="post">
        <input type="email" name="username">
        <input type="password" name="password">
        <input type="hidden" name="_csrf" value="${_csrf.token}">
        <input type="submit" value="Login">
    </form>
    <a href="/registration">Registration</a>
</body>
</html>